server:
  port: 8092

spring:
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 127.0.0.1 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: admin # RabbitMQ 服务的账号
    password: admin123 # RabbitMQ 服务的密码

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8&serverTimeZone=GMT&useSSL=true
      username: root
      password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
